language: node_js
node_js:
  - '10'
branches:
  only:
    - master
cache:
  yarn: true
script:
  - git config --global user.name "${GH_NAME2}"
  - echo "machine github.com login ${GH_NAME2} password ${GH_TOKEN2}" > ~/.netrc
  - cd website && yarn install && GIT_USER="${GH_NAME2}" yarn run publish-gh-pages
