language: node_js
node_js:
  - '10'
branches:
  only:
    - master
cache:
  yarn: true
script:
  #disable remove to activate# - git config --global user.name "${GH_NAME}"
  #disable# - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  #disable# - cd website && yarn install && GIT_USER="${GH_NAME}" yarn run publish-gh-pages
